version: '3.0'
services:
  kumo-agent:
    image: nefilim/kumo-agent:latest
    container_name: kumo-agent
    network_mode: host
    volumes:
       - 'application.conf:/opt/docker/conf/application.conf'
    restart: unless-stopped
